# >>> 设置目录树
GET_TARGET_PROPERTY(TARGET_SOURCES ${TARGET_NAME} SOURCES)
SOURCE_GROUP(TREE ${CMAKE_CURRENT_SOURCE_DIR} FILES ${SOURCE_FILES} ${HEADER_FILES})
SOURCE_GROUP("" FILES main.cpp static/DBDiffTool.rc)
# <<< 设置目录树

# >>> 导出
STRING(REPLACE " " "-" CMAKE_GENERATOR_MODIFIED "${CMAKE_GENERATOR}")
MESSAGE(STATUS "创建路径: ${CMAKE_GENERATOR_MODIFIED}")
SET(EXPORT_DIR ${PROJECT_SOURCE_DIR}/project/${CMAKE_GENERATOR_MODIFIED})
FILE(REMOVE ${EXPORT_DIR})
FILE(MAKE_DIRECTORY ${EXPORT_DIR})

FILE(GLOB VCX_PROJ
     ${CMAKE_BINARY_DIR}/*.sln
     ${CMAKE_BINARY_DIR}/*.vcxproj
     ${CMAKE_BINARY_DIR}/*.filters)

FOREACH(file IN LISTS VCX_PROJ)
  MESSAGE(STATUS "${WHT}${file}${RST}")
  FILE(COPY ${file} DESTINATION ${EXPORT_DIR})
ENDFOREACH()
# <<< 导出